### ISSUE TITLE
Individual search creates error message when searching by Sex and Org

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#320]
**Expected Behavior**
1. go to Individual search
2. use at metadata > organization filter and one additional filter (testing was done with gender)
3. Click submit
4. Search results page displays and individual records are accurately filtered.

**Current Behavior**
1. go to Individual search
2. use at metadata > organization filter and one additional filter (testing was done with gender)
3. Click submit
4. new page opens, exception is thrown (see technical investigation) and page does not display anything correctly except the exception and the footer contents.

_Technical Investgation_
When org filtered combined with another filter, the following is thrown, preventing the search results page from displaying:
`Exception thrown when executing query : SELECT DISTINCT 'org.ecocean.MarkedIndividual' AS "NUCLEUS_TYPE","A0"."INDIVIDUALID","A0"."INDIVIDUALID" AS "NUCORDER0" FROM "MARKEDINDIVIDUAL" "A0" CROSS JOIN "USERS" "VAR_USER" CROSS JOIN "ORGANIZATION" "VAR_ORG" WHERE EXISTS (SELECT 1 FROM "ENCOUNTER" "A0_SUB" INNER JOIN "MARKEDINDIVIDUAL_ENCOUNTERS" "B0_SUB" ON "A0_SUB"."CATALOGNUMBER" = "B0_SUB"."CATALOGNUMBER_EID" WHERE "B0_SUB"."INDIVIDUALID_OID" = "A0"."INDIVIDUALID") AND "VAR_USER"."USERNAME" = "A0_SUB"."SUBMITTERID" AND EXISTS (SELECT 1 FROM "USERS" "A0_SUB" INNER JOIN "ORGANIZATION_MEMBERS" "B0_SUB" ON "A0_SUB"."UUID" = "B0_SUB"."USER_ID" WHERE "B0_SUB"."ORGANIZATION_ID" = "VAR_ORG"."ID" AND "A0_SUB"."UUID" = "VAR_USER"."UUID") AND "VAR_ORG"."ID" = '2df48dd8-90ad-436c-8bfd-f556368705e4' AND NOT "A0"."SEX" LIKE 'male%' ESCAPE E'\\' AND NOT "A0"."SEX" LIKE 'unknown%' ESCAPE E'\\' AND "A0"."SEX" IS NOT NULL ORDER BY "NUCORDER0"`

With just org filter, the query looks like this:
`SELECT FROM org.ecocean.MarkedIndividual WHERE encounters.contains(enc) && user.username == enc.submitterID && org.members.contains(user) && org.id == '2df48dd8-90ad-436c-8bfd-f556368705e4' VARIABLES org.ecocean.Encounter enc; org.ecocean.User user; org.ecocean.Organization org`

Jason suspects error is in the mapping layer of the database. Potential solutions could be as simple as changing the order of the search query or require an upgrade of the relational mapping software.

Possibly related to https://github.com/WildMeOrg/Wildbook/issues/325
```
Exception on IndividualSearchResults!
javax.jdo.JDOException: Exception thrown when executing query : SELECT DISTINCT 'org.ecocean.MarkedIndividual' AS "NUCLEUS_TYPE","A0"."INDIVIDUALID","A0"."INDIVIDUALID" AS "NUCORDER0" FROM "MARKEDINDIVIDUAL" "A0" CROSS JOIN "USERS" "VAR_USER" CROSS JOIN "ORGANIZATION" "VAR_ORG" WHERE EXISTS (SELECT 1 FROM "ENCOUNTER" "A0_SUB" INNER JOIN "MARKEDINDIVIDUAL_ENCOUNTERS" "B0_SUB" ON "A0_SUB"."CATALOGNUMBER" = "B0_SUB"."CATALOGNUMBER_EID" WHERE "B0_SUB"."INDIVIDUALID_OID" = "A0"."INDIVIDUALID") AND "VAR_USER"."USERNAME" = "A0_SUB"."SUBMITTERID" AND EXISTS (SELECT 1 FROM "USERS" "A0_SUB" INNER JOIN "ORGANIZATION_MEMBERS" "B0_SUB" ON "A0_SUB"."UUID" = "B0_SUB"."USER_ID" WHERE "B0_SUB"."ORGANIZATION_ID" = "VAR_ORG"."ID" AND "A0_SUB"."UUID" = "VAR_USER"."UUID") AND "VAR_ORG"."ID" = '26fb922d-3feb-441f-b7fd-6b612fe3129f' AND NOT "A0"."SEX" LIKE 'male%' ESCAPE E'\\'  AND NOT "A0"."SEX" LIKE 'unknown%' ESCAPE E'\\'  AND "A0"."SEX" IS NOT NULL ORDER BY "NUCORDER0"
        at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:677)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:388)
        at org.datanucleus.api.jdo.JDOQuery.executeWithMap(JDOQuery.java:276)
        at org.ecocean.Shepherd.getAllMarkedIndividuals(Shepherd.java:3590)
        at org.ecocean.IndividualQueryProcessor.processQuery(IndividualQueryProcessor.java:1402)
        at org.apache.jsp.individualSearchResults_jsp._jspService(individualSearchResults_jsp.java:176)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.ecocean.servlet.StrutsUTF8Filter.doFilter(StrutsUTF8Filter.java:33)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
NestedThrowablesStackTrace:
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "A0_SUB"
  Position: 459
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
```

**QA Notes**

**Community Link**
https://community.wildme.org/t/search-error-when-selecting-gender-as-a-filter/2387

**Comment by goddesswarship** [comment]
Verified this is still present in ACW (10.3.0) & Whiskerbook (10.2.0) as originally reported. Bug is also present in Flukebook (10.2.0) and Sharkbook 10.5.3)
